plugins {
    id 'java-gradle-plugin'
    id("com.vanniktech.maven.publish") version "0.30.0"
}

group = 'com.sweetraingarden.gplugin'
def artifactId = 'moduledot'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation gradleApi()
    implementation 'org.jgrapht:jgrapht-core:1.5.1'
    implementation 'org.jgrapht:jgrapht-io:1.5.1'
    
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.10.1'
    testImplementation 'org.mockito:mockito-core:5.10.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.10.0'
}

tasks.withType(Copy).configureEach {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

test {
    useJUnitPlatform()
}

gradlePlugin {
    plugins {
        moduledot {
            id = "$group.$artifactId"
            implementationClass = 'com.sweetraingarden.gplugin.moduledot.ModuleDotPlugin'
            displayName = 'Module Dependency Graph Generator'
            description = 'Generates a DOT graph of module dependencies in an Gradle project'
        }
    }
}

//publishing {
//    publications {
//        maven(MavenPublication) {
//            groupId = group
//            artifactId = artifactId
//            version = version
//        }
//    }
//    repositories {
//        maven {
//            url = uri("https://github.com/SweetRainGarden/SweetraingardenGradleModuledot.git")
//        }
//    }
//}

// <module directory>/build.gradle.kts

mavenPublishing {
    publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL)

    signAllPublications()

    coordinates(group.toString(), artifactId, version.toString())

    pom {
        name = "Fibonacci library"
        description = "A mathematics calculation library."
        inceptionYear = "2025"
        url = "https://github.com/SweetRainGarden/SweetraingardenGradleModuledot.git"

        developers {
            developer {
                id = "SweetRainGarden"
                name = "Sweet Rain Garden"
                url = "https://github.com/SweetRainGarden"
            }
        }
        scm {
            url = "https://github.com/SweetRainGarden/SweetraingardenGradleModuledot.git"
            connection = "scm:git:git://github.com/SweetRainGarden/SweetraingardenGradleModuledot.git"
            developerConnection = "scm:git:ssh://git@github.com/SweetRainGarden/SweetraingardenGradleModuledot.git"
        }
    }
}